apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka-service
spec:
  type: ClusterIP
  ports:
  - name: kafka-port
    port: 9092
    targetPort: 9092
  selector:
    app: kafka

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-service:2181"
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://:9092"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-service.default.svc.cluster.local:9092"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_DELETE_TOPIC_ENABLE
            value: "true"
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 50m
            memory: 512Mi